### ISSUE TITLE
AssertionError: Not using `sparse_categorical_crossentropy` function for loss.

### ISSUE THREAD

**Issue by adil-official** [pradeepsinngh/Machine-Translation-with-Keras#3]
Getting this error on running with same code, but there's something wrong with loss function.

<img width="1555" alt="Screenshot 2020-06-20 at 10 13 35 PM" src="https://user-images.githubusercontent.com/57794292/85207638-5cd70e80-b343-11ea-90f0-490573a0a1c2.png">

**Comment by pradeepsinngh** [comment]
@ADIL-CUI Thanks a lot for the update. I'm in the process of updating this repo, please give me few days.

**Comment by adil-official** [comment]
@pradeepsinngh Can you please share why it's showing this error or something that i can try on my end to solve it because i have to create a report on different models of machine translation for my master assignment.
Thanks.

**Comment by pradeepsinngh** [comment]
Hi @ADIL-CUI,

You can check this repo again.. I have updated / edited the entire codebase to support TF 2.0. Let me know if face any issues. Thanks.
